import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";
import Provider from "./provider/Provider";
import { getAuthUser } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Product Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const loggedUser = getAuthUser()
  

  return (
    <html lang="en">
      <Provider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-gray-800`}
        >
          {/* Root wrapper must be fixed height */}
          <div className="flex h-screen overflow-hidden">
            {/* ================= Sidebar ================= */}
            <Sidebar />

            {/* ================= Content Area ================= */}
            <div className="flex-1 flex flex-col overflow-hidden">
              {/* Navbar (fixed, no scroll) */}
              <div className="shrink-0">
                <Navbar user = {loggedUser} ></Navbar>
              </div>

              {/* Main Content (ONLY THIS SCROLLS) */}
              <main className="flex-1 overflow-y-auto  ">{children}</main>
              <Footer />
            </div>
          </div>
        </body>
      </Provider>
    </html>
  );
}
